# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp

xsd2php:
  namespaces:
    '': 'MediaStoreNet\OpenImmo\Classes'
  destinations_php:
    'MediaStoreNet\OpenImmo\Classes': src/Classes
  #    'TestNs\MyApp': soap\src  #  on Windows

  destinations_jms:
    'MediaStoreNet\OpenImmo\Classes': src/Metadata
  naming_strategy: long
