# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp

xsd2php:
  namespaces:
    '': 'MediaStoreNet\OpenImmo'
  destinations_php:
    'MediaStoreNet\OpenImmo': src/classes
  #    'TestNs\MyApp': soap\src  #  on Windows

  destinations_jms:
    'MediaStoreNet\OpenImmo': src/metadata
  naming_strategy: long
